// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrnkTG_CXhW7IRvWln2ToUtsq8s7DmORA',
    appId: '1:729605836483:web:ce11be04c8156a308e9c76',
    messagingSenderId: '729605836483',
    projectId: 'ecosaathi-862d8',
    authDomain: 'ecosaathi-862d8.firebaseapp.com',
    storageBucket: 'ecosaathi-862d8.firebasestorage.app',
    measurementId: 'G-3VF43NFBEK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz700e3UZRZi2DTo0aVsPC0t07RV_Bo2U',
    appId: '1:729605836483:android:204a4f78927c538f8e9c76',
    messagingSenderId: '729605836483',
    projectId: 'ecosaathi-862d8',
    storageBucket: 'ecosaathi-862d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdk9rR7RV9UkqjQXNveMrMM_gidoqUgL8',
    appId: '1:729605836483:ios:0f658a449e5ba51d8e9c76',
    messagingSenderId: '729605836483',
    projectId: 'ecosaathi-862d8',
    storageBucket: 'ecosaathi-862d8.firebasestorage.app',
    iosBundleId: 'com.example.pictFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdk9rR7RV9UkqjQXNveMrMM_gidoqUgL8',
    appId: '1:729605836483:ios:0f658a449e5ba51d8e9c76',
    messagingSenderId: '729605836483',
    projectId: 'ecosaathi-862d8',
    storageBucket: 'ecosaathi-862d8.firebasestorage.app',
    iosBundleId: 'com.example.pictFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrnkTG_CXhW7IRvWln2ToUtsq8s7DmORA',
    appId: '1:729605836483:web:9778a0749188befe8e9c76',
    messagingSenderId: '729605836483',
    projectId: 'ecosaathi-862d8',
    authDomain: 'ecosaathi-862d8.firebaseapp.com',
    storageBucket: 'ecosaathi-862d8.firebasestorage.app',
    measurementId: 'G-YK7NZT8X7K',
  );

}